version: '3'
services: 
    web:
        container_name: "web"
        build:
            dockerfile: "./container/web/Dockerfile"
        ports:
            - "8000:80"
        volumes: 
            - "./src:/var/www/html"
    php:
        container_name: "php"
        build:
            dockerfile: "./container/php/Dockerfile"
        ports:
            - "5173:5173"
        volumes:
            - "./src:/var/www/html"
    db:
        container_name: "db"
        build:
          dockerfile: "./container/db/Dockerfile"
        ports:
          - "3306:3306"
        environment:
          - "MYSQL_ROOT_PASSWORD=password"
          - "MYSQL_DATABASE=meal-suggestion"
          - "MYSQL_USER=root"
          - "MYSQL_PASSWORD=password"
        volumes:
          - "./container/db/data:/var/lib/mysql"